var ChainTypes;

module.exports = ChainTypes = {};

ChainTypes.reserved_spaces = {
  relative_protocol_ids: 0,
  protocol_ids: 1,
  implementation_ids: 2
};

ChainTypes.operations= {
    vote: 0,
    comment: 1,
    transfer: 2,
    transfer_to_vesting: 3,
    withdraw_vesting: 4,
    limit_order_create: 5,
    limit_order_cancel: 6,
    feed_publish: 7,
    convert: 8,
    account_create: 9,
    account_update: 10,
    witness_update: 11,
    account_witness_vote: 12,
    account_witness_proxy: 13,
    pow: 14,
    custom: 15,
    report_over_production: 16,
    delete_comment: 17,
    custom_json: 18,
    comment_options: 19,
    set_withdraw_vesting_route: 20,
    limit_order_create2: 21,
    challenge_authority: 22,
    prove_authority: 23,
    request_account_recovery: 24,
    recover_account: 25,
    change_recovery_account: 26,
    escrow_transfer: 27,
    escrow_dispute: 28,
    escrow_release: 29,
    pow2: 30,
    escrow_approve: 31,
    transfer_to_savings: 32,
    transfer_from_savings: 33,
    cancel_transfer_from_savings: 34,
    custom_binary: 35,
    decline_voting_rights: 36,
    reset_account: 37,
    set_reset_account: 38,
    comment_benefactor_reward: 39,
    delegate_vesting_shares: 40,
    account_create_with_delegation: 41,
    comment_payout_extension: 42,
    asset_create: 43,
    asset_update: 44,
    asset_update_bitasset: 45,
    asset_update_feed_producers: 46,
    asset_issue: 47,
    asset_reserve: 48,
    asset_fund_fee_pool: 49,
    asset_settle: 50,
    asset_force_settle: 51,
    asset_global_settle: 52,
    asset_publish_feed: 53,
    asset_claim_fees: 54,
    call_order_update: 55,
    account_whitelist: 56,
    override_transfer: 57,
    proposal_create: 58,
    proposal_update: 59,
    proposal_delete: 60,
    fill_convert_request: 61,
    author_reward: 62,
    curation_reward: 63,
    comment_reward: 64,
    liquidity_reward: 65,
    interest: 66,
    fill_vesting_withdraw: 67,
    fill_order: 68,
    shutdown_witness: 69,
    fill_transfer_from_savings: 70,
    hardfork: 71,
    comment_payout_update: 72,
    return_vesting_delegation: 73,
    asset_settle_cancel: 74,
    fill_call_order: 75,
    fill_settlement_order: 76
};

//types.hpp
ChainTypes.object_type = {
  "null": 0,
  base: 1,
};
